### ISSUE TITLE
check for duplicated IDs

### ISSUE THREAD

**Issue by smgogarten** [UW-GAC/dbgaptools#12]
Would be helpful to have a check if SAMPLE_ID and SUBJECT_ID are unique in the sample-level and subject-level files, respectively.

**Comment by sarahcn** [comment]
check_sattr and check_ssm identify duplicate samples; check_pheno identifies duplicate subject ID. but looks like there needs to be additional checks for (1) duplicate subject in subject consent file and possibly (2) duplicate subject in pedigree file (though i wonder if GWASTools::pedigree_check already takes care of that

**Comment by smgogarten** [comment]
GWASTools::pedigree_check does not check for duplicates, so do it here

**Comment by smgogarten** [comment]
Fixed in e3b3421
