### ISSUE TITLE
read_dd_file fails for DD with no "VALUES" column

### ISSUE THREAD

**Issue by smgogarten** [UW-GAC/dbgaptools#9]
The line
```
idx <- (grep("VALUES", names(dd), ignore.case=TRUE) + 1):ncol(dd)
```
gives the error `argument of length 0`

**Comment by sarahcn** [comment]
@smgogarten Should be fixed now.
https://github.com/UW-GAC/dbgaptools/commit/0124c2e931931614c48c127300a7aec5c6c0547d

**Comment by smgogarten** [comment]
Now it's failing for a single column of VALUES. In that case,
```
grep("VALUES", names(dd), ignore.case=TRUE)
```
has the same value as `ncol(dd)`, so `idx` will end up being `5 4` and we try to index a nonexistent column. I think we want:
```
val.col <- grep("VALUES", names(dd), ignore.case=TRUE)
if (val.col > ncol(dd)) {
    idx <- (val.col + 1):ncol(dd)
    ...
}
```

**Comment by sarahcn** [comment]
I tweaked your suggested fix; please try again. Thanks! 
https://github.com/UW-GAC/dbgaptools/commit/6758f7563b820226dc99d6aacd56e6dd6b9221d0

**Comment by smgogarten** [comment]
Working, thanks!
